settings:
  entity-metadata:
    - 'VISIBLE_FOR_GHOSTS'
    - 'HIDDEN_FOR_LIVING'
stages:
# check if this necromancer has competence for given ghost
  start:
    actions:
      A:
        type: CHECK_IF_GHOST
        args:
          onfailure: noghost
      B:
        type: CHECK_GRAVEYARD_COMPETENCE
        args:
          onsuccess: success
          onfailure: wronggraveyard

# player is no ghost
  noghost:
    text: 'Ich spreche nur mit Geistern!'
# inform ghost about wrong graveyard
  wronggraveyard:
    text: 'Ich kann dein Körper nicht wiederbeleben.|Du musst zum Friedhof %[graveyard] gehen und dort mit dem Geisterbeschwörer reden!'
    actions:
      A:
        type: END

# revive ghost
  success:
    text: 'Bist du dir sicher das ich dich hier wiederbeleben soll?|Wenn du zu deiner Leiche gehst hast du die Chance deine Items zurück zu bekommen.'
    answers:
      1:
        text: 'Ja erweck mich wieder zum Leben'
        actions:
          A:
            type: REVIVE_GHOST
            args:
              delay: 15
      2:
        text: 'Nein ich möchte doch meine Leiche suchen'
        actions:
          A:
            type: TEXT
            args:
              text: 'Viel Glück dabei!'
          B:
            type: END